# Generated by Django 3.1 on 2020-09-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=300)),
                ('poster_name', models.CharField(max_length=40)),
                ('poster_email', models.CharField(max_length=40)),
                ('poster_code', models.CharField(max_length=6)),
            ],
        ),
    ]
